version: '3.8'

services:
  php-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php-app
    restart: unless-stopped
    networks:
      - appnet
    depends_on:
      - mysql
    expose:
      - "8102"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-app
    networks:
      - appnet

  mysql:
    image: mysql:8.0
    container_name: simba-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kel1
      MYSQL_USER: kel1_user
      MYSQL_PASSWORD: kel1_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - appnet

  go-simba-chat-backend:
    build:
      context: ./Simba-chatting/backend
      dockerfile: backendDockerfile
    container_name: go-simba-chat-backend
    restart: unless-stopped
    networks:
      - appnet
    ports:
      - "8080:8080"
    expose:
      - "8080"

  js-simba-chatting:
    build:
      context: ./Simba-chatting
      dockerfile: ../Simba-chattingDockerfile
    container_name: js-simba-chatting
    restart: unless-stopped
    init: true
    networks:
      - appnet
    ports:
      - "3000:3000"
    depends_on:
      - go-simba-chat-backend

volumes:
  mysql-data:

networks:
  appnet:
    driver: bridge