services:
  simba-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: simba-app
    restart: unless-stopped
    networks:
      - appnet
    depends_on:
      - mysql
    ports:
      - "80:80"

  mysql:
    image: mysql:8.4
    container_name: simba-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: kel1
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - appnet
    ports:
      - "3307:3306"  # Avoids conflict with local MySQL/MariaDB if any

volumes:
  mysql-data:

networks:
  appnet:
    driver: bridge