services:
  php-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php-app
    restart: unless-stopped
    init: true
    # env_file: ./.env  # Uncomment if .env file exists
    ports:
      - "8000:8000"  # Laravel's built-in server
    networks:
      - simba-net
    depends_on:
      - mysql-db
    # The app expects a MySQL database, see README and .env.example

  go-simba-chat-backend:
    build:
      context: ./Simba-chatting/backend
      dockerfile: backendDockerfile
    container_name: go-simba-chat-backend
    restart: unless-stopped
    ports:
      - "8080:8080"  # Go backend service
    networks:
      - simba-net
    # env_file: ./Simba-chatting/backend/.env  # Uncomment if .env file exists

  js-simba-chatting:
    build:
      context: ./Simba-chatting
      dockerfile: Simba-chattingDockerfile
    container_name: js-simba-chatting
    restart: unless-stopped
    init: true
    ports:
      - "3000:3000"  # React frontend
    networks:
      - simba-net
    # env_file: ./Simba-chatting/.env  # Uncomment if .env file exists

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: kel1
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - simba-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    # The database name, user, and password are based on .env.example and README

networks:
  simba-net:
    driver: bridge

volumes:
  mysql-data:
    # Persistent storage for MySQL
